# 報告ツール設定ファイル
# かならず文字コードは UTF-8 または UTF-8N で保存してください。
# メモ帳でも編集・保存できます
# 注）パスワードは暗号化して保存するようになりました。
# 　　パスワードを変更は、config.yaml をリネームまたは削除してから
# 　　報告ツールを実行し、登録済みのアカウントを設定することで行えます
--- 
account: 
  name: 
  password: 
database: 
  file_path: ../*.db
replay: 
  is_send_replay:
  config_path: 
  